import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../public/flows.js',import.meta.url),'utf8').replace(/bootstrap\(\);\s*$/,'');
function harness(){let forms=[];const context=vm.createContext({location:{pathname:'/employer/applications/1',search:''},window:{matchMedia:()=>({addEventListener(){}}),addEventListener(){}},document:{addEventListener(){},querySelectorAll:selector=>selector.includes('data-dirty')?forms.filter(f=>f.dataset.dirty==='true'):forms,querySelector:()=>forms.find(f=>f.dataset.dirty==='true')}});vm.runInContext(source,context);return {context,setForms:value=>forms=value};}
function form(kind,value,type='textarea'){const field={name:'body',value,type};const elements=[field];elements.namedItem=name=>elements.find(el=>el.name===name);return {dataset:{form:kind,id:'1',dirty:'true'},elements};}
test('saving one application form preserves a separate draft without persisting secrets',async()=>{const h=harness(),message=form('message','Unsent candidate message'),note=form('note','Saved note'),password=form('password','private-secret','password');h.setForms([message,note,password]);assert.equal(h.context.captureFormDrafts().find(d=>d.kind==='password').fields.length,0);h.context.savedForm=note;vm.runInContext('render=async()=>{captured=captureFormDrafts()}',h.context);await vm.runInContext('refreshSubmittedForm(savedForm)',h.context);assert.equal(h.context.captured.some(d=>d.kind==='note'),false);const fresh=form('message','');delete fresh.dataset.dirty;h.setForms([fresh]);h.context.restoreFormDrafts(h.context.captured);assert.equal(fresh.elements[0].value,'Unsent candidate message');assert.equal(vm.runInContext('formChanged',h.context),true);});
test('login destinations distinguish public employers page from private employer workspace',()=>{const h=harness();Object.assign(h.context,{isEmployer:()=>false,isStaff:()=>false,base:()=>'/dashboard',intendedDestination:()=>'/employers'});assert.equal(h.context.safeNext(),'/employers');h.context.intendedDestination=()=>'/employer/jobs';assert.equal(h.context.safeNext(),'/dashboard');});
