import {hashPassword,now,transaction,audit,notify} from './db.mjs';
import path from 'node:path';

export function registerMarketplace(app,c){
 const {db,auth,loginLimit,session,safeUser,text,email,password,jobFields,fail,countryValues,stages}=c;
 const employer=(req,res,next)=>{if(req.user?.role!=='employer')return res.status(req.user?403:401).json({error:'Sign in with a company account.'});req.company=db.prepare('SELECT * FROM companies WHERE owner_id=?').get(req.user.id);if(!req.company)return res.status(403).json({error:'Company account is unavailable. Contact support.'});next();};
 const ownedJob=(req,id)=>{const j=db.prepare('SELECT * FROM jobs WHERE id=? AND company_id=?').get(id,req.company.id);if(!j)fail(404,'This role was not found in your company.');return j;};
 const ownedApplication=(req,id)=>{const a=db.prepare(`SELECT a.*,u.name,u.email,u.headline,u.location AS candidate_location,u.skills,u.bio,j.title AS job_title,j.location,j.country,j.currency,j.salary_min,j.salary_max,j.period,d.name AS document_name,d.parse_status FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users u ON u.id=a.user_id LEFT JOIN documents d ON d.id=a.document_id WHERE a.id=? AND j.company_id=?`).get(id,req.company.id);if(!a)fail(404,'Application not found in your company.');delete a.analysis;return a;};
 const ownedInterview=(req,id)=>{const i=db.prepare('SELECT i.* FROM interviews i JOIN applications a ON a.id=i.application_id JOIN jobs j ON j.id=a.job_id WHERE i.id=? AND j.company_id=?').get(id,req.company.id);if(!i)fail(404,'Interview not found in your company.');return i;};
 const admin=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({error:'Administrator access required.'});
 app.get('/api/admin/companies',admin,(req,res)=>res.json({companies:db.prepare('SELECT c.id,c.name,c.country,c.created_at,u.email,u.active,COUNT(j.id) AS jobs FROM companies c JOIN users u ON u.id=c.owner_id LEFT JOIN jobs j ON j.company_id=c.id GROUP BY c.id ORDER BY c.id DESC').all()}));
 app.patch('/api/admin/companies/:id',admin,(req,res)=>{const company=db.prepare('SELECT * FROM companies WHERE id=?').get(req.params.id);if(!company)fail(404,'Company not found.');if(typeof req.body.active!=='boolean')fail(422,'Choose a valid account status.');transaction(db,()=>{db.prepare('UPDATE users SET active=? WHERE id=?').run(req.body.active?1:0,company.owner_id);if(!req.body.active){db.prepare('DELETE FROM sessions WHERE user_id=?').run(company.owner_id);db.prepare("UPDATE jobs SET status='closed',updated_at=? WHERE company_id=? AND status='published'").run(now(),company.id);}audit(db,req.user.id,req.body.active?'Company access restored':'Company suspended',company.id);});res.json({ok:true});});
 app.post('/api/auth/register-employer',loginLimit,async(req,res)=>{
  if(req.user)fail(409,'Sign out before creating a different account.');
  const b=req.body,name=text(b.name,100),mail=email(b.email),company=text(b.company,150),country=text(b.country,100);
  if(b.consent!==true)fail(422,'Please accept the privacy notice.');if(!countryValues.has(country))fail(422,'Select your company country.');
  const hash=await hashPassword(password(b.password));
  if(db.prepare('SELECT id FROM users WHERE email=?').get(mail))fail(409,'This email already has an account. Sign in or use a separate work email.');
  const user=transaction(db,()=>{const id=Number(db.prepare("INSERT INTO users(name,email,password,role,created_at) VALUES(?,?,?,'employer',?)").run(name,mail,hash,now()).lastInsertRowid);db.prepare('INSERT INTO companies(owner_id,name,country,created_at,updated_at) VALUES(?,?,?,?,?)').run(id,company,country,now(),now());audit(db,id,'Company account created',company);return db.prepare('SELECT * FROM users WHERE id=?').get(id);});
  session(res,user);res.status(201).json({user:safeUser(user)});
 });
 app.get('/api/companies/:id',(req,res)=>{const company=db.prepare('SELECT id,name,website,description,location,country,sector FROM companies WHERE id=?').get(req.params.id);if(!company)fail(404,'Company not found.');const jobs=db.prepare("SELECT * FROM jobs WHERE company_id=? AND status='published' ORDER BY created_at DESC").all(company.id);res.json({company,jobs});});
 app.get('/api/employer/company',employer,(req,res)=>res.json({company:req.company}));
 app.patch('/api/employer/company',employer,(req,res)=>{
  const b=req.body,name=text(b.name,150),country=text(b.country,100),website=text(b.website||'',500,false);
  if(!countryValues.has(country))fail(422,'Select a valid country.');if(website){try{const u=new URL(website);if(u.protocol!=='https:'||u.username||u.password)throw Error();}catch{fail(422,'Use a full HTTPS company website address.');}}
  transaction(db,()=>{db.prepare('UPDATE companies SET name=?,website=?,description=?,location=?,country=?,sector=?,updated_at=? WHERE id=?').run(name,website,text(b.description||'',5000,false),text(b.location||'',120,false),country,text(b.sector||'',100,false),now(),req.company.id);db.prepare('UPDATE jobs SET company=?,updated_at=? WHERE company_id=?').run(name,now(),req.company.id);audit(db,req.user.id,'Company profile updated',req.company.id);});res.json({ok:true});
 });
 app.get('/api/employer/jobs',employer,(req,res)=>res.json({jobs:db.prepare('SELECT j.*,COUNT(a.id) AS applicant_count FROM jobs j LEFT JOIN applications a ON a.job_id=j.id WHERE j.company_id=? GROUP BY j.id ORDER BY j.id DESC').all(req.company.id)}));
 const values=(req)=>jobFields({...req.body,company:req.company.name,featured:false});
 app.post('/api/employer/jobs',employer,(req,res)=>{const v=values(req);if(db.prepare("SELECT COUNT(*) AS n FROM jobs WHERE company_id=? AND status!='closed'").get(req.company.id).n>=100)fail(422,'Close an existing role before creating more than 100 active or draft roles.');const id=Number(db.prepare('INSERT INTO jobs(title,company,sector,location,country,currency,salary_min,salary_max,period,workplace,type,description,requirements,benefits,status,featured,created_at,updated_at,company_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...v,now(),now(),req.company.id).lastInsertRowid);audit(db,req.user.id,'Company role created',id);res.status(201).json({id});});
 app.patch('/api/employer/jobs/:id',employer,(req,res)=>{ownedJob(req,req.params.id);db.prepare('UPDATE jobs SET title=?,company=?,sector=?,location=?,country=?,currency=?,salary_min=?,salary_max=?,period=?,workplace=?,type=?,description=?,requirements=?,benefits=?,status=?,featured=?,updated_at=? WHERE id=? AND company_id=?').run(...values(req),now(),req.params.id,req.company.id);audit(db,req.user.id,'Company role updated',req.params.id);res.json({ok:true});});
 app.get('/api/employer/applications',employer,(req,res)=>res.json({applications:db.prepare('SELECT a.id,a.job_id,a.status,a.created_at,a.updated_at,u.name,u.email,u.headline,j.title AS job_title,j.country FROM applications a JOIN jobs j ON j.id=a.job_id JOIN users u ON u.id=a.user_id WHERE j.company_id=? ORDER BY a.created_at DESC').all(req.company.id)}));
 app.get('/api/employer/applications/:id',employer,(req,res)=>{const a=ownedApplication(req,req.params.id);res.json({application:a,notes:db.prepare('SELECT n.*,u.name AS author FROM notes n JOIN users u ON u.id=n.author_id WHERE n.application_id=? AND n.author_id=? ORDER BY n.id DESC').all(a.id,req.user.id),interviews:db.prepare('SELECT * FROM interviews WHERE application_id=? ORDER BY starts_at').all(a.id)});});
 app.patch('/api/employer/applications/:id',employer,(req,res)=>{const a=ownedApplication(req,req.params.id),status=req.body.status;if(!stages.includes(status)||status==='Withdrawn')fail(422,'Choose a valid hiring stage.');if(a.status==='Withdrawn')fail(409,'The candidate withdrew this application.');transaction(db,()=>{db.prepare('UPDATE applications SET status=?,updated_at=? WHERE id=?').run(status,now(),a.id);if(status==='Declined')db.prepare("UPDATE interviews SET status='Cancelled' WHERE application_id=? AND status='Scheduled'").run(a.id);notify(db,a.user_id,'Application update',`${req.company.name}: ${a.job_title} — ${status}.`);audit(db,req.user.id,'Company application updated',a.id);});res.json({ok:true});});
 app.post('/api/employer/applications/:id/notes',employer,(req,res)=>{const a=ownedApplication(req,req.params.id);db.prepare('INSERT INTO notes(application_id,author_id,body,created_at) VALUES(?,?,?,?)').run(a.id,req.user.id,text(req.body.body,5000),now());res.status(201).json({ok:true});});
 app.get('/api/employer/applications/:id/cv',employer,(req,res)=>{const a=ownedApplication(req,req.params.id);const d=db.prepare('SELECT * FROM documents WHERE id=?').get(a.document_id);if(!d)fail(404,'No CV is attached.');res.set({'Content-Type':d.mime,'Content-Disposition':`attachment; filename="cv${path.extname(d.name)}"; filename*=UTF-8''${encodeURIComponent(d.name)}`});res.send(Buffer.from(d.data));});
 app.get('/api/employer/interviews',employer,(req,res)=>res.json({interviews:db.prepare('SELECT i.*,u.name AS candidate_name,j.title AS job_title FROM interviews i JOIN applications a ON a.id=i.application_id JOIN users u ON u.id=a.user_id JOIN jobs j ON j.id=a.job_id WHERE j.company_id=? ORDER BY i.starts_at').all(req.company.id)}));
 app.post('/api/employer/interviews',employer,(req,res)=>{const b=req.body,a=ownedApplication(req,Number(b.application_id)),date=new Date(b.starts_at),duration=Number(b.duration),zone=text(b.timezone,80);if(['Withdrawn','Declined','Hired'].includes(a.status))fail(409,'This application is closed.');if(!Number.isFinite(date.getTime())||date.getTime()<=Date.now()||![15,30,45,60,90].includes(duration))fail(422,'Choose a future date and valid duration.');try{new Intl.DateTimeFormat('en',{timeZone:zone});}catch{fail(422,'Choose a valid timezone.');}const start=date.toISOString(),end=new Date(date.getTime()+duration*60000).toISOString();if(db.prepare("SELECT i.id FROM interviews i JOIN applications a ON a.id=i.application_id WHERE i.status='Scheduled' AND (i.recruiter_id=? OR a.user_id=?) AND i.starts_at<? AND datetime(i.starts_at,'+' || i.duration || ' minutes')>datetime(?)").get(req.user.id,a.user_id,end,start))fail(409,'This time overlaps an existing interview.');const location=text(b.location,500),notes=text(b.notes||'',2000,false);transaction(db,()=>{db.prepare('INSERT INTO interviews(application_id,recruiter_id,starts_at,duration,timezone,location,notes,created_at) VALUES(?,?,?,?,?,?,?,?)').run(a.id,req.user.id,start,duration,zone,location,notes,now());db.prepare("UPDATE applications SET status='Interview',updated_at=? WHERE id=?").run(now(),a.id);notify(db,a.user_id,'Interview scheduled',`${req.company.name}: ${a.job_title}. View your interview details.`,'/dashboard/interviews');});res.status(201).json({ok:true});});
 app.patch('/api/employer/interviews/:id',employer,(req,res)=>{const i=ownedInterview(req,req.params.id),status=req.body.status;if(!['Cancelled','Completed'].includes(status))fail(422,'Choose a valid interview status.');if(i.status!=='Scheduled')fail(409,'This interview is already closed.');db.prepare('UPDATE interviews SET status=? WHERE id=?').run(status,i.id);const a=ownedApplication(req,i.application_id);notify(db,a.user_id,`Interview ${status.toLowerCase()}`,a.job_title,'/dashboard/interviews');res.json({ok:true});});
 app.get('/api/matches',auth,(req,res)=>{if(req.user.role!=='candidate')fail(403,'Job matching is available to candidates.');const skills=[...new Set(req.user.skills.toLowerCase().split(/[,\n]/).map(x=>x.trim()).filter(Boolean))];const jobs=db.prepare("SELECT * FROM jobs WHERE status='published' ORDER BY created_at DESC").all().map(j=>{const haystack=` ${j.title} ${j.requirements} `.toLowerCase();const matched=skills.filter(skill=>{const escaped=skill.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|[^a-z0-9])${escaped}($|[^a-z0-9])`,'i').test(haystack);});return {...j,matchedSkills:matched};}).filter(j=>j.matchedSkills.length).sort((a,b)=>b.matchedSkills.length-a.matchedSkills.length);res.json({jobs,skills});});
}
