import {createRequire} from 'node:module';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createApp} from '../platform/app.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const dir=await mkdtemp(path.join(os.tmpdir(),'blackstone-journey-'));
const origin='http://127.0.0.1:4181';
const {app,db}=await createApp({dataDir:dir,demo:true,testing:true,origin});
const server=app.listen(4181,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const settled=()=>page.waitForFunction(()=>document.querySelector('#content')&&!document.body.classList.contains('loading'));
const go=async p=>{await page.goto(origin+p);await settled();};
try{
 await go('/jobs');
 await page.locator('#job-country').selectOption('UAE');
 await page.locator('#job-sector').selectOption('Technology');
 await page.locator('#job-workplace').selectOption('Hybrid');
 await page.locator('#job-search').fill('Figma');
 assert.ok(page.url().includes('sector=Technology'));
 await page.reload();await settled();assert.equal(await page.locator('#job-country').inputValue(),'UAE');assert.equal(await page.locator('#job-sector').inputValue(),'Technology');assert.equal(await page.locator('#job-workplace').inputValue(),'Hybrid');
 const jobHref=await page.locator('.job-card h3 a').first().getAttribute('href');
 await page.locator('.job-card h3 a').first().click();await settled();
 await page.getByRole('link',{name:'← All opportunities'}).click();await settled();assert.equal(await page.locator('#job-search').inputValue(),'Figma');
 await page.getByRole('button',{name:'Clear filters'}).click();assert.equal(new URL(page.url()).search,'');
 await go(jobHref);await page.getByRole('button',{name:'Apply for this role'}).click();await page.waitForURL('**/login?**');await settled();
 await page.locator('.auth-bottom a').click();await page.waitForURL('**/register?**');await settled();
 assert.equal(new URL(page.url()).searchParams.get('next'),jobHref);
 await page.locator('#name').fill('Journey Candidate');await page.locator('#email').fill('journey@example.com');await page.locator('#password').fill('JourneyCandidate!2026');
 await page.getByRole('button',{name:/Show Password/}).click();assert.equal(await page.locator('#password').getAttribute('type'),'text');
 await page.locator('[name=consent]').check();await page.getByRole('button',{name:'Create my account'}).click();await page.waitForURL(origin+jobHref);await settled();
 await page.getByRole('button',{name:'Apply for this role'}).click();await page.locator('#modal[open]').waitFor();
 assert.equal(await page.locator('#modal [type=submit]').isDisabled(),true);
 await page.locator('#cover').fill('Please keep this introduction while I upload my CV.');
 await page.locator('#application-cv').setInputFiles({name:'wrong.exe',mimeType:'application/octet-stream',buffer:Buffer.from('wrong')});
 assert.match(await page.locator('[data-upload-status]').innerText(),/Choose a PDF/);
 await page.locator('#application-cv').setInputFiles({name:'journey.txt',mimeType:'text/plain',buffer:Buffer.from('Journey Candidate. Product design, Figma and user research experience.')});
 await page.waitForFunction(()=>!document.querySelector('#modal [type=submit]').disabled);
 assert.equal(await page.locator('#cover').inputValue(),'Please keep this introduction while I upload my CV.');
 assert.equal(new URL(page.url()).pathname,jobHref);
 await page.screenshot({path:'qa/platform/journey-inline-application.png'});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('#modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.locator('#modal [name=consent]').check();await page.locator('#modal [type=submit]').click();await page.waitForURL('**/dashboard/applications/*');await settled();
 assert.equal(db.prepare("SELECT COUNT(*) n FROM applications a JOIN users u ON a.user_id=u.id WHERE u.email='journey@example.com'").get().n,1);
 await go(jobHref);assert.equal(await page.getByRole('button',{name:'Apply for this role'}).count(),0);assert.equal(await page.getByRole('link',{name:'View your application'}).count(),1);
 await go('/dashboard');assert.equal(await page.getByRole('region',{name:'Getting started'}).count(),1);
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'qa/platform/journey-candidate-next-steps.png'});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/login');await settled();
 await page.getByRole('button',{name:'Explore recruiter workspace'}).click();await page.waitForURL('**/workspace');await settled();
 await page.locator('.pipeline-row').filter({hasText:'Applied'}).click();await page.waitForURL('**/workspace/applications?stage=Applied');await settled();assert.equal(await page.locator('#application-stage').inputValue(),'Applied');
 await page.getByRole('button',{name:'Pipeline',exact:true}).click();await page.reload();await settled();assert.equal(await page.locator('.kanban-column').count(),1);
 await go(jobHref);assert.equal(await page.getByRole('link',{name:'Manage this role'}).count(),1);assert.equal(await page.getByRole('button',{name:'Apply for this role'}).count(),0);
 await page.locator('.nav-actions').getByRole('link',{name:'Workspace',exact:true}).click();await page.waitForURL('**/workspace');await settled();
 assert.deepEqual(errors,[]);
 console.log('Journey audit passed: retained filters, login/register return path, password visibility, inline CV validation/upload, preserved introduction, application tracking, duplicate prevention, mobile modal, onboarding, recruiter stage links and board persistence.');
}catch(error){await page.screenshot({path:'qa/platform/journey-failure.png',fullPage:true});throw error;}
finally{await browser.close();await new Promise(r=>server.close(r));db.close();await rm(dir,{recursive:true,force:true});}
