import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const settled=()=>page.waitForFunction(()=>document.querySelector('#content')&&!document.body.classList.contains('loading'));
try {
  await page.goto('http://127.0.0.1:4174/'); await settled();
  const switchedAt=Date.now();
  await page.locator('.public-nav a[href="/jobs"]').click();
  await page.locator('.brand-curtain').waitFor({state:'visible'});
  await page.waitForTimeout(450);
  await page.screenshot({path:'qa/platform/branded-page-transition.png'});
  await settled();
  assert.ok(Date.now()-switchedAt>=950,'Branded page transition holds for about one second');
  assert.equal(await page.locator('.brand-curtain').count(),0);
  assert.equal(await page.locator('#app').evaluate(el=>el.inert),false);
  assert.equal(new URL(page.url()).pathname,'/jobs');
  await page.evaluate(()=>{navigate('/approach');navigate('/employers');navigate('/jobs');});
  await settled();
  assert.equal(new URL(page.url()).pathname,'/jobs');
  assert.ok(await page.locator('#job-search').count());
  await page.locator('#job-search').fill('Figma');
  assert.ok(await page.locator('.job-card').count());
  assert.equal(await page.locator('.job-card').first().evaluate(el=>getComputedStyle(el).opacity),'1');
  await page.locator('.public-nav .brand').click(); await settled();
  await page.locator('.cta-band').scrollIntoViewIfNeeded();
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('.cta-band').evaluate(el=>getComputedStyle(el).opacity),'1');
  await page.screenshot({path:'qa/platform/motion-scroll.png'});
  await page.locator('.footer-links a[href="/approach"]').click(); await settled();
  assert.equal(await page.evaluate(()=>scrollY),0);
  await page.goBack(); await settled();
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>!document.querySelector('.motion-pending'));
  assert.equal(await page.locator('.motion-pending').count(),0);
  await page.locator('.public-nav a[href="/employers"]').click(); await settled();
  assert.equal(await page.locator('.motion-pending').count(),0);
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.addInitScript(()=>{document.startViewTransition=undefined;});
  await page.goto('http://127.0.0.1:4174/'); await settled();
  await page.locator('.public-nav a[href="/jobs"]').click(); await settled();
  assert.ok(await page.locator('#job-search').count());
  await page.goto('http://127.0.0.1:4174/'); await settled();
  await page.waitForTimeout(1500);
  await page.screenshot({path:'qa/platform/motion-home.png'});
  assert.deepEqual(errors,[]);
  console.log('Motion QA passed: rapid navigation, filtering visibility, scroll reveals, route scroll reset, history, reduced motion and browser fallback.');
} finally {await browser.close();}
